In [3]:
import pandas as pd
from plotly.express import pie, scatter
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("/content/tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df = pd.get_dummies(df, columns=['sex', 'smoker', 'day', 'time'], dtype=int)

missing_columns = ['day_Mon', 'day_Tues', 'day_Wed', 'time_Breakfast']
df.loc[:, missing_columns] = 0
df = df.drop(columns=["sex_Male", "smoker_No"])
df.head()

,total_bill,tip,size,sex_Female,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch,day_Mon,day_Tues,day_Wed,time_Breakfast
0,16.99,1.01,2,1,0,0,0,1,0,1,0,0,0,0,0
1,10.34,1.66,3,0,0,0,0,1,0,1,0,0,0,0,0
2,21.01,3.50,3,0,0,0,0,1,0,1,0,0,0,0,0
3,23.68,3.31,2,0,0,0,0,1,0,1,0,0,0,0,0
4,24.59,3.61,4,1,0,0,0,1,0,1,0,0,0,0,0

In [6]:
fig = scatter(
    df,
    x="total_bill",
    y="tip"
)
fig.show()

In [7]:
day_cols = [
    "day_Fri", "day_Sat", "day_Sun", "day_Thur",
    "day_Mon", "day_Tues", "day_Wed"
]

day_counts = df[day_cols].sum().reset_index()
day_counts.columns = ["Day", "Count"]

fig = pie(
    day_counts,
    values="Count",
    names="Day",
    title="Distribution of Visits by Weekday"
)

fig.show()

In [8]:
X, y = df.drop(columns=["tip"]), df["tip"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R²:", r2)
print("MAE:", mae)
print("MSE:", mse)

R²: 0.43730181943482516
MAE: 0.6671331480264895
MSE: 0.7033566017436103